# Configuration of the app
app:
    name: fixstudio_wiki
    description: ''
    website: ''
    websiteAlt: ''
    charset: 'utf-8'
    indexing: 'noindex, nofollow'
    darkmode:
        theme: 
            - light
            - dark
        cookie: 
            mode: THEME_MODE
    admin:
        email: ''
    hosts:
        allowed:
            - '*'
        excluded: {  }
    css:
        framework:
            source: github
            author: kekefreedog
            package: Kmaterialize
            branch: advanced
            theme: vertical-gradient-menu
    template:
        engine:
            php:
                source: github
                author: zordius
                package: lightncandy
            js:
                package: handlebars
        root: resources/hbs
        extension: hbs
    auth:
        type: Kauth
    adobe:
        pdf: 5e88a369cf3e447ea27869b6621595d3