# Configuration of the app
app:
    name: fixstudio_wiki
    description: ''
    website: ''
    websiteAlt: ''
    charset: 'utf-8'
    indexing: 'noindex, nofollow'
    darkmode:
        theme: 
            - light
            - dark
        cookie: 
            mode: THEME_MODE
    admin:
        email: ''
    hosts:
        allowed:
            - '*'
        excluded: {  }
    css:
        framework:
            source: github
            author: kekefreedog
            package: Kmaterialize
            branch: advanced
            theme: vertical-gradient-menu
    template:
        engine:
            php:
                source: github
                author: zordius
                package: lightncandy
            js:
                package: handlebars
        root: resources/hbs
        extension: hbs
    auth:
        type: Kauth
    adobe:
        pdf: 0f361e250c4d4582b09f36f0dbc5d7d3
    shotgrid:
        - 
            name: wizz
            host: https://wizz.shotgunstudio.com
            auth:
                client_id: fix_doc
                client_secret: pqfFtwmoyimwm(3bgpnldyaoq
                grant_type: client_credentials
    rocketchat:
        url: https://chat.fixstudio.com
        login: kzarshenas
        password: Fixstudio33
