# Page of the app
page:
    head:
        default: main
        branches:
            main:
                -
                    tag: meta
                    attributes:
                        charset: 'utf-8'
                -
                    tag: meta
                    attributes:
                        http-equiv: X-UA-Compatible
                        content: IE=edge
                -
                    tag: meta
                    attributes:
                        name: viewport
                        content:
                            width: device-width
                            initial-scale: 1.0
                            user-scalable: 0
                            minimal-ui: null
                -
                    tag: meta
                    attributes:
                        name: application-name
                        content: '{{app.name}}'
                -
                    tag: meta
                    attributes:
                        name: theme-color
                        content: '#2196f3'
                -
                    tag: meta
                    attributes:
                        name: description
                        content: '{{app.description}}'
                -
                    tag: meta
                    attributes:
                        name: robots
                        content: '{{app.indexing}}'
                -
                    tag: meta
                    attributes:
                        name: googlebot
                        content: '{{app.indexing}}'
                -
                    tag: meta
                    attributes:
                        name: google
                        content: notranslate
                -
                    tag: meta
                    attributes:
                        name: google-site-verification
                        content: Tr4iJ1jgJkXy8p6apd_kKwTxvIBJllokc9EvvrsLbUU
                -
                    tag: meta
                    attributes:
                        name: rating
                        content: General
                -
                    tag: link
                    attributes:
                        rel: manifest
                        href: /manifest.json
                # Favicon
                -
                    tag: link
                    attributes:
                        rel: apple-touch-icon
                        sizes: 180x180
                        href: /media/favicon/apple-touch-icon
                -
                    tag: link
                    attributes:
                        rel: icon
                        type: image/png
                        sizes: 32x32
                        href: /media/favicon/favicon-32x32
                -
                    tag: link
                    attributes:
                        rel: icon
                        type: image/png
                        sizes: 16x16
                        href: /media/favicon/favicon-16x16
                -
                    tag: link
                    attributes:
                        rel: mask-icon
                        href: /media/favicon/safari-pinned-tab
                        color: "#5bbad5"
                -
                    tag: meta
                    attributes:
                        name: msapplication-TileColor
                        content: "#000000"
                -
                    tag: meta
                    attributes:
                        name: theme-color
                        content: "#ffffff"
