# Rootes of the app
routes:
    -
        name: Home
        patterns:
            - /index/
        methods:
            - get
        response: html
    -
        name: Login
        patterns:
            - /login/
        methods:
            - get
        response: html
    -
        name: Info
        patterns:
            - /api/
        methods:
            - get
        response: json
    -
        name: Logo
        patterns:
            - /media/logo/[a:logo_name]/
        methods:
            - get
        response: data
    -
        name: 'Page not found'
        patterns:
            - '/*/'
        methods:
            - '*'
        response: html
methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTION
    - PATCH
