# Rootes of the app
routes:
    -   # Home
        name: Home
        patterns:
            - /index/
        methods:
            - get
        response: html
    -   # Tutorial
        name: Tutorial
        patterns:
            - /tutorial/
        methods:
            - get
        response: html
    -   # Tutorial
        name: TutorialSection
        patterns:
            - /tutorial/[a:name]
        methods:
            - get
        response: html
    -   # Reade file
        name: Media
        patterns:
            - /drive/[a:root0]/media/[a:name]
            - /drive/[a:root0]/[a:root1]/media/[a:name]
            - /drive/[a:root0]/[a:root1]/[a:root2]/media/[a:name]
            - /drive/[a:root0]/[a:root1]/[a:root2]/[a:root3]/media/[a:name]
        methods:
            - get
        response: data
    -   # Google Drive Page
        name: Drive
        patterns:
            - /drive/[a:root0]/
            - /drive/[a:root0]/[a:root1]
            - /drive/[a:root0]/[a:root2]/[a:root3]
            - /drive/[a:root0]/[a:root2]/[a:root3]/[a:root4]
        methods:
            - get
        response: html
    # - # Google Drive Page
    #     name: Login
    #     patterns:
    #         - /login/
    #     methods:
    #         - get
    #     response: html
    -   # Sidenav Get
        name: Sidenav
        patterns:
            - /api/sidenav/
        methods:
            - get
        response: json
    -   # Sidenav change
        name: SidenavChange
        patterns:
            - /api/sidenav/[a:status]/
        methods:
            - post
        response: json
    -   # SG Projects
        name: sgProjects
        patterns:
            - /api/shotgrid/projects/
        methods:
            - get
        response: json
    -   # Theme change
        name: ThemeChange
        patterns:
            - /api/theme/[a:status]/
        methods:
            - post
        response: json
    -   # file / info
        name: FileDrive
        patterns:
            - /api/file/drive/[a:id]/
        methods:
            - get
        response: json
    -   # Read logo
        name: Logo
        patterns:
            - /media/logo/[a:logo_name]/
        methods:
            - get
        response: data
    -   # Read ressources
        name: Ressources
        patterns:
            - /media/ressources/[a:media_name]/
        methods:
            - get
        response: data
    -   # Reade file
        name: File
        patterns:
            - /media/file/
        methods:
            - get
        response: data
    -   # All others pages
        name: 'Page not found'
        patterns:
            - '/*/'
        methods:
            - '*'
        response: html
methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTION
    - PATCH
